name: Update Spotify Status

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-spotify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Spotify Status
        uses: novatorem/novatorem@main
        with:
          CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          # Ensures standard dark mode formatting
          THEME: dark
